name: Bug report
about: Create a report to help us improve
title: "[BUG]:"
labels: ["bug"]
assignees: 
- team 3
body:
- type: markdown
  attributes:
    value: |
      **Test Case used**
      Refer to the test case name and id if it correspond to a test case.  

      **Severity**
      The different scaling of severity
      1 - low
      2 - medium
      3 - high
      4 - critical

- type: textarea
  attributes:
    label: Describe the issue
    description: A clear and concise description of what the issue is.

- type: input
  attributes:
    label: Arduino Device Details
    description: Please provide the following details
  validations:
    required: true

- type: textarea
  attributes:
    label: To Reproduce
    description: Steps to reproduce the behavior.

- type: textarea
  attributes:
    label: Expected behavior
    description: A clear and concise description of what you expected to happen.

- type: textarea
  attributes:
    label: Actual behavior
    description: A clear and concise description of what happened actually.

- type: textarea
  attributes:
    label: Screenshots
    description: If applicable, add screenshots to help explain your problem.

- type: textarea
  attributes:
    label: Additional context
    description: Add any other context about the problem here.

- type: textarea
  attributes:
    label: Potential solution
    description: If any, propose a potential solution.
