name: Bug report
description: "Create a report to help fixing bugs"
title: "BUG"
labels: ["bug"]
body:

  - type: input
  id: testcase
  attributes:
    label: Test Case
    description:  enter the test case name and id if any

  - type: dropdown
  id: severity
  attributes:
    label: Severity
    description: Please select the severity of this issue
    options:
      - low
      - medium
      - high
      - critical
  validations:
    required: true

- type: textarea
  attributes:
    label: Describe the issue
    description: A clear and concise description of what the issue is.

- type: input
  attributes:
    label: Arduino Device Details
    description: Please provide the following details
  validations:
    required: true

- type: textarea
  attributes:
    label: To Reproduce
    description: Steps to reproduce the behavior.

- type: textarea
  attributes:
    label: Expected behavior
    description: A clear and concise description of what you expected to happen.

- type: textarea
  attributes:
    label: Actual behavior
    description: A clear and concise description of what happened actually.

- type: textarea
  attributes:
    label: Screenshots
    description: If applicable, add screenshots to help explain your problem.

- type: textarea
  attributes:
    label: Additional context
    description: Add any other context about the problem here.

- type: textarea
  attributes:
    label: Potential solution
    description: If any, propose a potential solution.
